project:
  type: website
  render:
    - index.qmd
  resources:
    - "assets/pdfs/*"
    - "data/*.yml"

website:
  title: "Quarto Template Gallery"
  navbar:
    right:
      - icon: github
        href: https://github.com/christopherkenny/template-gallery
        aria-label: GitHub repository

format:
  html:
    theme: cosmo
    css: assets/gallery.css
    toc: false
